### ISSUE TITLE
Online DOC

### ISSUE THREAD

**Issue by CarlosZiegler** [n26/psd2-tpp-docs#20]
Hello, 

I implemented a example for this DOC using redoc and vecel. I added  rest of DOC but need refinament .

Here is the deployed version: https://psd2-doc.vercel.app/
Repo: https://github.com/CarlosZiegler/psd2-doc

Idea is to have an online version of the documentation. Using redoc to use openapi and show API features. I also added basic from the other documentation that is in markdown format. Idea will be to either render mdx or put examples inside the openapi file. But that would be just an idea.

Here is the principal API doc : https://psd2-doc.vercel.app/docs/openapi

**Comment by NomvuzoMaitin** [comment]
Hi Carlos, thanks for the suggestion! 

In future, you can contact the team directly using this [form](https://docs.google.com/forms/d/e/1FAIpQLSeUSRcrJqMQ-Uf8IOic-7fNvKl8SzJJruwECbHFGPLlPH0SQw/viewform).
