### ISSUE TITLE
Th 401 Unauthorized Error

### ISSUE THREAD

**Issue by Agachily** [n26/psd2-tpp-docs#7]
Hi,

I am trying to initiate authorization using the "Get /oauth2/authorize" endpoint.  I am sure that I have made the request properly and used a valid QWAC certificate. However, I keep on meeting the 401 "Unauthorized" when I launch the request. I have enclosed the certificate I used in the attachments, and the request and response are as follows:

Request:
Request('https://xs2a.tech26.de/sandbox/oauth2/authorize?client_id=PSDFI-FINFSA-29884997&scope=DEDICATED_AISP&code_challenge=Ko-ZDNq86TL04htViGKGZFFCXyQN-KZLm7_RQZI6oBQ&redirect_uri=https%3A%2F%2Fenablebanking.com%2Fauth_redirect&response_type=CODE&state=e1aba161-8df2-467c-bdc8-43760a19dde7', b'', headers={'PSU-IP-Address': '10.10.10.10', 'PSU-IP-Port': '443', 'PSU-User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15', 'PSU-GEO-Location': 'GEO:0.0,0.0', 'Accept': 'application/json', 'X-Request-ID': '3322e1ec-a5c5-11ec-95c3-362ec41f7aea', 'User-Agent': 'enable:Banking/0.11.0/python'}, method='GET', tls={'cert': '/Users/zhaozetong/Work/sdk-generator/tests/assets/qwac.pem', 'key': '/Users/zhaozetong/Work/sdk-generator/tests/assets/qwac.key'})

Response:
401 ''

Thanks very much!

**Comment by NomvuzoMaitin** [comment]
Hi,

I'm sorry you're facing this issue. Please could you contact the Open Banking team for support via [this form](https://docs.google.com/forms/d/e/1FAIpQLSeUSRcrJqMQ-Uf8IOic-7fNvKl8SzJJruwECbHFGPLlPH0SQw/viewform).

Thank you!
